   version: '3.8'
   services:
     webapi:
       image: catalogmsssolution:dev
       ports:
         - "5000:80"
     nginx:
       image: nginx
       ports:
         - "8080:80"
       volumes:
         - ./nginx.conf:/etc/nginx/nginx.conf:ro
       depends_on:
         - webapi
